import type { Question } from "./types";

export const DEMO_TITLE = "青年小組冰破";

export const DEMO_QUESTIONS: Question[] = [
  {
    id: "bible-10",
    category: "bible",
    points: 10,
    prompt: "耶穌喺邊個海面上行路？",
    answer: "加利利海",
    accept: ["加利利", "Galilee", "Sea of Galilee", "革尼撒勒"],
    hostNote: "太14 / 可6 / 約6",
    askFor: "text",
  },
  {
    id: "bible-30",
    category: "bible",
    points: 30,
    prompt: "舊約中，邊個喺獅子坑裏面仍然平安？",
    answer: "但以理",
    accept: ["但以理", "Daniel", "但尼爾"],
    hostNote: "但以理書 6",
    askFor: "text",
  },
  {
    id: "bible-50",
    category: "bible",
    points: 50,
    prompt: "「主是我的牧者，我必不至缺乏」出自詩篇第幾篇？",
    answer: "詩篇 23 篇",
    accept: ["23", "詩篇23", "Psalm 23", "廿三"],
    hostNote: "詩篇 23:1",
    askFor: "text",
  },
  {
    id: "pop-10",
    category: "pop",
    points: 10,
    prompt: "為何坐到那麼近 卻想得這樣遠",
    answer: "想得太遠",
    accept: ["想得太遠", "容祖兒 想得太遠"],
    hostNote: "容祖兒《想得太遠》",
    askFor: "song",
  },
  {
    id: "pop-30",
    category: "pop",
    points: 30,
    prompt: "每段戀愛都會認錯人",
    answer: "失戀王",
    accept: ["失戀王", "陳小春 失戀王"],
    hostNote: "陳小春《失戀王》",
    askFor: "song",
  },
  {
    id: "pop-50",
    category: "pop",
    points: 50,
    prompt: "甚麼叫絕望抬起眼望望",
    answer: "絕",
    accept: ["絕", "傅珮嘉 絕"],
    hostNote: "傅珮嘉《絕》",
    askFor: "song",
  },
  {
    id: "kdrama-10",
    category: "kdrama",
    points: 10,
    prompt: "呢張劇照係邊套劇？（示範可無真實劇照）",
    answer: "愛的迫降",
    accept: ["愛的迫降", "Crash Landing on You", "CLOY"],
    hostNote: "答劇名",
    imageUrl: "/kdrama/cloy.jpg",
    askFor: "title",
  },
  {
    id: "kdrama-30",
    category: "kdrama",
    points: 30,
    prompt: "呢個角色叫咩名？",
    answer: "金智榮",
    accept: ["金智榮", "김지영", "Kim Ji-young"],
    hostNote: "答角色名；示範題",
    imageUrl: "/kdrama/jiyoung.jpg",
    askFor: "character",
  },
  {
    id: "kdrama-50",
    category: "kdrama",
    points: 50,
    prompt: "呢張劇照係邊套劇？",
    answer: "黑暗榮耀",
    accept: ["黑暗榮耀", "The Glory"],
    hostNote: "答劇名；示範題",
    imageUrl: "/kdrama/glory.jpg",
    askFor: "title",
  },
  {
    id: "pun-10",
    category: "pun",
    points: 10,
    prompt: "一個人跳落水，但頭髮完全冇濕，點解？",
    answer: "因為佢冇頭髮",
    accept: ["冇頭髮", "沒有頭髮", "光頭", "禿頭"],
    hostNote: "冷笑話，接近即可",
    askFor: "punchline",
  },
  {
    id: "pun-30",
    category: "pun",
    points: 30,
    prompt: "姓陳同姓李兩個人寫情信，但最終只有一個人有勇氣寄出去，係邊個？",
    answer: "姓李，因為李敢寄",
    accept: ["姓李", "李", "李敢寄"],
    hostNote: "諧音：李敢寄；接近即可",
    askFor: "punchline",
  },
  {
    id: "pun-50",
    category: "pun",
    points: 50,
    prompt: "你阿媽係熊，你阿爸係貓，咁你係咩？",
    answer: "魚，因為錦鯉係魚",
    accept: ["魚", "錦鯉", "錦鯉係魚", "你係魚"],
    hostNote: "諧音：熊＋貓＝熊貓，再諧音錦鯉；接近即可",
    askFor: "punchline",
  },
];
