import type { Question } from "./types";

export const DEMO_TITLE = "青年小組冰破";

export const DEMO_QUESTIONS: Question[] = [
  {
    id: "bible-10",
    category: "bible",
    points: 10,
    prompt: "耶穌喺邊個海面上行路？",
    answer: "加利利海",
    accept: ["加利利", "Galilee", "Sea of Galilee", "革尼撒勒"],
    hostNote: "太14 / 可6 / 約6",
    askFor: "text",
  },
  {
    id: "bible-30",
    category: "bible",
    points: 30,
    prompt: "舊約中，邊個喺獅子坑裏面仍然平安？",
    answer: "但以理",
    accept: ["但以理", "Daniel", "但尼爾"],
    hostNote: "但以理書 6",
    askFor: "text",
  },
  {
    id: "bible-50",
    category: "bible",
    points: 50,
    prompt: "「主是我的牧者，我必不至缺乏」出自詩篇第幾篇？",
    answer: "詩篇 23 篇",
    accept: ["23", "詩篇23", "Psalm 23", "廿三"],
    hostNote: "詩篇 23:1",
    askFor: "text",
  },
  {
    id: "pop-10",
    category: "pop",
    points: 10,
    prompt: "「你問我愛你有幾深，我愛你有幾分……」",
    answer: "月亮代表我的心",
    accept: ["月亮代表我的心"],
    hostNote: "鄧麗君",
    askFor: "song",
  },
  {
    id: "pop-30",
    category: "pop",
    points: 30,
    prompt: "「明天你是否會想起，昨天你寫的日記……」",
    answer: "童年",
    accept: ["童年"],
    hostNote: "羅大佑",
    askFor: "song",
  },
  {
    id: "pop-50",
    category: "pop",
    points: 50,
    prompt: "「誰能憑愛意要富士山私有……」",
    answer: "喜歡你",
    accept: ["喜歡你"],
    hostNote: "Beyond",
    askFor: "song",
  },
  {
    id: "kdrama-10",
    category: "kdrama",
    points: 10,
    prompt: "呢張劇照係邊套劇？（示範可無真實劇照）",
    answer: "愛的迫降",
    accept: ["愛的迫降", "Crash Landing on You", "CLOY"],
    hostNote: "答劇名",
    imageUrl: "/kdrama/cloy.jpg",
    askFor: "title",
  },
  {
    id: "kdrama-30",
    category: "kdrama",
    points: 30,
    prompt: "呢個角色叫咩名？",
    answer: "金智榮",
    accept: ["金智榮", "김지영", "Kim Ji-young"],
    hostNote: "答角色名；示範題",
    imageUrl: "/kdrama/jiyoung.jpg",
    askFor: "character",
  },
  {
    id: "kdrama-50",
    category: "kdrama",
    points: 50,
    prompt: "呢張劇照係邊套劇？",
    answer: "黑暗榮耀",
    accept: ["黑暗榮耀", "The Glory"],
    hostNote: "答劇名；示範題",
    imageUrl: "/kdrama/glory.jpg",
    askFor: "title",
  },
  {
    id: "pun-10",
    category: "pun",
    points: 10,
    prompt: "點解聖經唔適合用來墊枱？",
    answer: "因為會「壓舊約」",
    accept: ["壓舊約", "壓過舊約"],
    hostNote: "諧音冷笑話，接近即可",
    askFor: "punchline",
  },
  {
    id: "pun-30",
    category: "pun",
    points: 30,
    prompt: "點解挪亞方舟上面啲動物都好有禮貌？",
    answer: "因為兩隻兩隻「請」上船",
    accept: ["兩隻兩隻請", "請上船"],
    hostNote: "冷笑話，接近即可",
    askFor: "punchline",
  },
  {
    id: "pun-50",
    category: "pun",
    points: 50,
    prompt: "點解教會 Wi-Fi 密碼唔應該設成 Amen？",
    answer: "因為會變成「阿們才能連」",
    accept: ["阿們才能連", "Amen"],
    hostNote: "冷笑話，接近即可",
    askFor: "punchline",
  },
];
